# Generated by Django 2.2.3 on 2019-07-08 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_full_name', models.CharField(max_length=200)),
                ('student_entrance_date', models.DateField(null=True)),
                ('student_exit_date', models.DateField(blank=True, null=True)),
                ('student_userpic_file_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_dt', models.DateTimeField()),
                ('discipline_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Schedule')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Student')),
            ],
        ),
    ]
