# Generated by Django 2.2.3 on 2019-08-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190801_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='presence',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='discipline_id',
            new_name='discipline',
        ),
    ]
