# Generated by Django 2.2.3 on 2019-08-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_bb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bb',
        ),
    ]
